# Generated by Django 3.0.2 on 2024-09-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_number',
            new_name='page_name',
        ),
    ]
