# Generated by Django 3.0.2 on 2024-08-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='comment',
            field=models.CharField(default='Not required', max_length=40),
        ),
    ]
